name: Run Cron Job

on: 
  schedule:
    - cron: '0 * * * *'

jobs: 
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API and save response
        id: fetch_data
        run: | 
          RESPONSE=$(curl -s "https://main.d1vajphj1n3pfj.amplifyapp.com/api/newsdata/intermilan" | jq -c .)
          curl -X POST "https://main.d1vajphj1n3pfj.amplifyapp.com/api/newsdata/overall" \
          -H "Content-Type: application/json" \
          -d "$RESPONSE"

        
