name: Run Cron Job

on: 
  schedule:
    - cron: '*/5 * * * *

jobs: 
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API and save response
        id: fetch_data
        run: | 
          RESPONSE=$(curl -s "https://main.d1vajphj1n3pfj.amplifyapp.com/api/newsdata/intermilan")
          echo "response=$RESPONSE" >> $GITHUB_ENV
        
      - name: Send response via POST
        run: |
          curl -X POST "https://main.d1vajphj1n3pfj.amplifyapp.com/api/newsdata/overall"
          -H "Content-Type: application/json" \
          -d "$GITHUB_ENV